apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsepocnodejs-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lsepoc
  template:
    metadata:
      labels:
        app: lsepoc
    spec:
      containers:
      - name: lsepoc-nodejs
        image: lsepocacr.azurecr.io/lsepocacr:15
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000