apiVersion : apps/v1
kind: Deployment
metadata:
  name: "canvaksdemo-c908"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "canvaksdemo-c908"
  template:
    metadata:
      labels:
        app: "canvaksdemo-c908"
    spec:
      containers:
        - name: "canvaksdemo-c908"
          image: "21101992.azurecr.io/canvaksdemo"
          ports:
          - containerPort: 3000