pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub_canv2110')
	}

	stages {

        stage('Docker build image') {
			steps {
				sh 'docker build -t canv2110/nodeapp_app:1.0 .'
			}
		}

		stage('Docker Hub Login') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Docker image push') {
			steps {
				sh 'docker push canv2110/nodeapp_app:1.0'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}