on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 21101992.azurecr.io
        username: ${{ secrets.acr_21101992_username }}
        password: ${{ secrets.acr_21101992_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t 21101992.azurecr.io/canvaksdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push 21101992.azurecr.io/canvaksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_canvaksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep canv-aks-demo9138 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace canv-aks-demo9138`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: canv-aks-demo9138
        container-registry-url: 21101992.azurecr.io
        container-registry-username: ${{ secrets.acr_21101992_username }}
        container-registry-password: ${{ secrets.acr_21101992_password }}
        secret-name: canvaksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: canv-aks-demo9138
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          21101992.azurecr.io/canvaksdemo:${{ github.sha }}
        imagepullsecrets: |
          canvaksdemodockerauth
